Upgrade 'canvas'
Ragg-/deream pull request #2
Opened 2019-11-07 09:23 UTC by MikuroXina

- Upgrade 'canvas' to 2.5.0
- Add yarn.lock
- Format
- Update this version to 0.0.3

2019-11-14 03:44 UTC, hanakla requested changes
Reviewed, Thanks for your PR!

2019-11-14 03:44 UTC, ra-gg commented on index.js
> +  if (options.args === null || options.args === undefined) {
You can do this

```suggestion
  if (options.args == null) {
```

2019-11-14 03:44 UTC, ra-gg commented on index.js
> +  if (options.dest === null || options.dest === undefined) {
```suggestion
  if (options.dest == null) {
```

2019-11-27 14:15 UTC, MikuroXina commented
Sorry, I think better that made the function using default values so I added a commit above.

2020-10-11 03:32 UTC, MikuroXina commented
I aborted this because replied nothing yet.

2020-10-11 03:32 UTC, closed without merging